### ISSUE TITLE
Google Maps 

### ISSUE THREAD

**Issue by krystynakono** [krmalewski/project2#1]
I want to import a google map into my project but I am unsure how to do this through the server because the only examples they give are building the map on the front end. 

I have been able to import a static map, but that is not really going to work for my project and I would rather imbed an actual map where the user can zoom in/out. 

The example given within the documentation shows the map being created as such:

![screen shot 2016-10-28 at 11 13 51 am](https://cloud.githubusercontent.com/assets/18222735/19811501/a992b458-9cff-11e6-87bd-b10b1cbf4c88.png)

I do not want to use this because my API_KEY will be visible, but I am also unsure how to implement node-fetch in a case where I am using constructors . 

@gittheking @jasonseminara @trevorpreston @irwintsay @rapala61

**Comment by krystynakono** [comment]
Dawa helped me with this! 

I ended up putting it inside of my ejs file. This will result in my API being public but there doesn't seem to be anything confidential associated with his key so I don't know if this is a major problem for this project. 

If going down this route is okay, then we can close the issue. If not, then I still need some support with how to use constructors to create a map on my page. 

Thank you! :)

**Comment by rapala61** [comment]
Yes, the google maps API key will have to be used in the front end. You should have access to manage which domains can and cannot use this API key. More info here: https://developers.google.com/maps/documentation/javascript/get-api-key
